package SysML2WorkbenchArchitecture {
    package SysML2Workbench {
        part def ViewDefinitionModel {
            doc /* Captures custom view type, expose targets, and filter expression. */

            comment sourceRef /* Source: src/DemaConsulting.SysML2Workbench/ViewBuilderSubsystem/ViewDefinitionModel.cs */
            comment testRef /* Test: test/DemaConsulting.SysML2Workbench.Tests/ViewBuilderSubsystem/ViewDefinitionModelTests.cs */
            comment designRef /* Design: docs/design/sysml2-workbench/view-builder-subsystem/view-definition-model.md */
            comment verificationRef /* Verification: docs/verification/sysml2-workbench/view-builder-subsystem/view-definition-model.md */
            comment reqRef /* Requirements: docs/reqstream/sysml2-workbench/view-builder-subsystem/view-definition-model.yaml */
        }
    }
}
